"""
Shared test fixtures for scan module tests.

Provides mock project trees, temporary directories, and common
test data for scanner unit tests.
"""

from __future__ import annotations

import json
import textwrap
from pathlib import Path
from typing import Any, Dict

import pytest


# ---------------------------------------------------------------------------
# Basic project fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def tmp_project(tmp_path: Path) -> Path:
    """Create a minimal temporary project directory."""
    return tmp_path


@pytest.fixture
def empty_project(tmp_path: Path) -> Path:
    """Create an empty temporary project directory."""
    return tmp_path


@pytest.fixture
def minimal_project(tmp_path: Path) -> Path:
    """Create a minimal project with just a README.md."""
    (tmp_path / "README.md").write_text("# Test Project\n")
    return tmp_path


# ---------------------------------------------------------------------------
# Language-specific project fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def node_project(tmp_path: Path) -> Path:
    """Create a Node.js project with express + react deps and CI.

    Includes: package.json (express, react), package-lock.json,
    .github/workflows/ci.yml
    """
    package_json = {
        "name": "test-node-project",
        "version": "1.0.0",
        "description": "A test Node.js project",
        "dependencies": {
            "express": "^4.18.0",
            "react": "^18.2.0",
        },
        "devDependencies": {
            "@nestjs/core": "^10.0.0",
        },
    }
    (tmp_path / "package.json").write_text(json.dumps(package_json, indent=2))
    (tmp_path / "package-lock.json").write_text("{}")

    # GitHub Actions CI
    workflows_dir = tmp_path / ".github" / "workflows"
    workflows_dir.mkdir(parents=True)
    (workflows_dir / "ci.yml").write_text(
        "name: CI\non: [push]\njobs:\n  test:\n    runs-on: ubuntu-latest\n"
    )
    return tmp_path


@pytest.fixture
def python_project(tmp_path: Path) -> Path:
    """Create a Python project with fastapi dep and requirements.txt.

    Includes: pyproject.toml (fastapi), requirements.txt
    """
    pyproject = textwrap.dedent("""\
        [project]
        name = "test-python-project"
        version = "1.0.0"
        description = "A test Python project"
        dependencies = [
            "fastapi>=0.100.0",
        ]
    """)
    (tmp_path / "pyproject.toml").write_text(pyproject)
    (tmp_path / "requirements.txt").write_text("fastapi>=0.100.0\nuvicorn>=0.23.0\n")
    return tmp_path


@pytest.fixture
def go_project(tmp_path: Path) -> Path:
    """Create a Go project with go.mod and go.sum.

    Includes: go.mod with module path, go.sum
    """
    go_mod = textwrap.dedent("""\
        module github.com/example/test-go-project

        go 1.21

        require github.com/gin-gonic/gin v1.9.1
    """)
    (tmp_path / "go.mod").write_text(go_mod)
    (tmp_path / "go.sum").write_text("github.com/gin-gonic/gin v1.9.1 h1:abc=\n")
    return tmp_path


@pytest.fixture
def rust_project(tmp_path: Path) -> Path:
    """Create a Rust project with Cargo.toml and Cargo.lock.

    Includes: Cargo.toml, Cargo.lock
    """
    cargo_toml = textwrap.dedent("""\
        [package]
        name = "test-rust-project"
        version = "0.1.0"
        description = "A test Rust project"
        edition = "2021"

        [dependencies]
        serde = "1.0"
    """)
    (tmp_path / "Cargo.toml").write_text(cargo_toml)
    (tmp_path / "Cargo.lock").write_text("# This file is automatically generated\n")
    return tmp_path


@pytest.fixture
def java_maven_project(tmp_path: Path) -> Path:
    """Create a Java project with pom.xml."""
    pom_xml = textwrap.dedent("""\
        <?xml version="1.0" encoding="UTF-8"?>
        <project>
            <modelVersion>4.0.0</modelVersion>
            <groupId>com.example</groupId>
            <artifactId>test-java-project</artifactId>
            <version>1.0.0</version>
        </project>
    """)
    (tmp_path / "pom.xml").write_text(pom_xml)
    return tmp_path


@pytest.fixture
def java_gradle_project(tmp_path: Path) -> Path:
    """Create a Java project with build.gradle."""
    (tmp_path / "build.gradle").write_text(
        "plugins { id 'java' }\nversion = '1.0.0'\n"
    )
    return tmp_path


@pytest.fixture
def php_project(tmp_path: Path) -> Path:
    """Create a PHP project with composer.json."""
    composer_json = {
        "name": "example/test-php-project",
        "description": "A test PHP project",
        "require": {"php": "^8.1"},
    }
    (tmp_path / "composer.json").write_text(json.dumps(composer_json, indent=2))
    return tmp_path


@pytest.fixture
def ruby_project(tmp_path: Path) -> Path:
    """Create a Ruby project with Gemfile."""
    (tmp_path / "Gemfile").write_text(
        'source "https://rubygems.org"\ngem "rails", "~> 7.0"\n'
    )
    return tmp_path


@pytest.fixture
def csharp_project(tmp_path: Path) -> Path:
    """Create a C#/.NET project with .csproj."""
    (tmp_path / "TestProject.csproj").write_text(
        '<Project Sdk="Microsoft.NET.Sdk">\n'
        "  <PropertyGroup>\n"
        "    <TargetFramework>net8.0</TargetFramework>\n"
        "  </PropertyGroup>\n"
        "</Project>\n"
    )
    return tmp_path


# ---------------------------------------------------------------------------
# Monorepo fixture
# ---------------------------------------------------------------------------


@pytest.fixture
def monorepo_project(tmp_path: Path) -> Path:
    """Create a monorepo with React frontend and FastAPI backend.

    Includes: turbo.json, apps/frontend/package.json (React),
    apps/backend/pyproject.toml (FastAPI)
    """
    # Turbo config
    (tmp_path / "turbo.json").write_text(json.dumps({"pipeline": {}}, indent=2))

    # Root package.json with workspaces
    root_pkg = {
        "name": "test-monorepo",
        "private": True,
        "workspaces": ["apps/*"],
    }
    (tmp_path / "package.json").write_text(json.dumps(root_pkg, indent=2))

    # Frontend (React)
    frontend_dir = tmp_path / "apps" / "frontend"
    frontend_dir.mkdir(parents=True)
    frontend_pkg = {
        "name": "@monorepo/frontend",
        "version": "1.0.0",
        "dependencies": {"react": "^18.2.0", "next": "^14.0.0"},
    }
    (frontend_dir / "package.json").write_text(json.dumps(frontend_pkg, indent=2))

    # Backend (FastAPI)
    backend_dir = tmp_path / "apps" / "backend"
    backend_dir.mkdir(parents=True)
    pyproject = textwrap.dedent("""\
        [project]
        name = "monorepo-backend"
        version = "1.0.0"
        dependencies = [
            "fastapi>=0.100.0",
        ]
    """)
    (backend_dir / "pyproject.toml").write_text(pyproject)

    return tmp_path


# ---------------------------------------------------------------------------
# Full DevOps project fixture
# ---------------------------------------------------------------------------


@pytest.fixture
def devops_project(tmp_path: Path) -> Path:
    """Create a full DevOps project with infrastructure, GitOps, and CI.

    Includes: package.json, Dockerfile, terraform/main.tf (GCP provider),
    gitops/clusters/dev/kustomization.yaml (Flux), .github/workflows/ci.yml
    """
    # Application
    pkg = {
        "name": "devops-app",
        "version": "1.0.0",
        "dependencies": {"express": "^4.18.0"},
    }
    (tmp_path / "package.json").write_text(json.dumps(pkg, indent=2))
    (tmp_path / "package-lock.json").write_text("{}")

    # Dockerfile
    (tmp_path / "Dockerfile").write_text("FROM node:20-alpine\nWORKDIR /app\n")

    # Terraform with GCP provider
    tf_dir = tmp_path / "terraform"
    tf_dir.mkdir()
    (tf_dir / "main.tf").write_text(
        textwrap.dedent("""\
            provider "google" {
              project = "my-gcp-project"
              region  = "us-central1"
            }

            resource "google_compute_instance" "default" {
              name         = "test"
              machine_type = "e2-medium"
            }
        """)
    )

    # GitOps with Flux (kustomization.yaml with toolkit.fluxcd.io)
    gitops_dir = tmp_path / "gitops" / "clusters" / "dev"
    gitops_dir.mkdir(parents=True)
    (gitops_dir / "kustomization.yaml").write_text(
        textwrap.dedent("""\
            apiVersion: kustomize.toolkit.fluxcd.io/v1
            kind: Kustomization
            metadata:
              name: dev-cluster
              namespace: flux-system
            spec:
              interval: 5m
              path: ./gitops/clusters/dev
              prune: true
        """)
    )

    # GitHub Actions CI
    workflows_dir = tmp_path / ".github" / "workflows"
    workflows_dir.mkdir(parents=True)
    (workflows_dir / "ci.yml").write_text(
        "name: CI\non: [push]\njobs:\n  test:\n    runs-on: ubuntu-latest\n"
    )

    return tmp_path


# ---------------------------------------------------------------------------
# Git directory fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def git_project_github(tmp_path: Path) -> Path:
    """Create a project with .git directory configured for GitHub.

    Sets up .git/config with origin remote pointing to github.com,
    .git/HEAD pointing to main, and branch refs.
    """
    git_dir = tmp_path / ".git"
    git_dir.mkdir()

    # Git config with origin remote
    config_content = textwrap.dedent("""\
        [core]
            repositoryformatversion = 0
            filemode = true
        [remote "origin"]
            url = git@github.com:example/test-project.git
            fetch = +refs/heads/*:refs/remotes/origin/*
        [remote "upstream"]
            url = https://github.com/upstream/test-project.git
            fetch = +refs/heads/*:refs/remotes/upstream/*
        [branch "main"]
            remote = origin
            merge = refs/heads/main
    """)
    (git_dir / "config").write_text(config_content)

    # HEAD points to main
    (git_dir / "HEAD").write_text("ref: refs/heads/main\n")

    # Branch refs
    refs_heads = git_dir / "refs" / "heads"
    refs_heads.mkdir(parents=True)
    (refs_heads / "main").write_text("abc123\n")

    refs_remotes_origin = git_dir / "refs" / "remotes" / "origin"
    refs_remotes_origin.mkdir(parents=True)
    (refs_remotes_origin / "main").write_text("abc123\n")

    return tmp_path


@pytest.fixture
def git_project_gitlab(tmp_path: Path) -> Path:
    """Create a project with .git directory configured for GitLab."""
    git_dir = tmp_path / ".git"
    git_dir.mkdir()

    config_content = textwrap.dedent("""\
        [remote "origin"]
            url = git@gitlab.com:group/project.git
            fetch = +refs/heads/*:refs/remotes/origin/*
    """)
    (git_dir / "config").write_text(config_content)
    (git_dir / "HEAD").write_text("ref: refs/heads/main\n")

    refs_heads = git_dir / "refs" / "heads"
    refs_heads.mkdir(parents=True)
    (refs_heads / "main").write_text("abc123\n")

    return tmp_path


@pytest.fixture
def git_project_bitbucket(tmp_path: Path) -> Path:
    """Create a project with .git directory configured for Bitbucket."""
    git_dir = tmp_path / ".git"
    git_dir.mkdir()

    config_content = textwrap.dedent("""\
        [remote "origin"]
            url = git@bitbucket.org:team/project.git
            fetch = +refs/heads/*:refs/remotes/origin/*
    """)
    (git_dir / "config").write_text(config_content)
    (git_dir / "HEAD").write_text("ref: refs/heads/master\n")

    refs_heads = git_dir / "refs" / "heads"
    refs_heads.mkdir(parents=True)
    (refs_heads / "master").write_text("abc123\n")

    return tmp_path


@pytest.fixture
def git_project_selfhosted(tmp_path: Path) -> Path:
    """Create a project with .git directory configured for self-hosted Git."""
    git_dir = tmp_path / ".git"
    git_dir.mkdir()

    config_content = textwrap.dedent("""\
        [remote "origin"]
            url = git@git.internal.company.com:team/project.git
            fetch = +refs/heads/*:refs/remotes/origin/*
    """)
    (git_dir / "config").write_text(config_content)
    (git_dir / "HEAD").write_text("ref: refs/heads/main\n")

    refs_heads = git_dir / "refs" / "heads"
    refs_heads.mkdir(parents=True)
    (refs_heads / "main").write_text("abc123\n")

    return tmp_path


@pytest.fixture
def git_project_gitflow(tmp_path: Path) -> Path:
    """Create a project with gitflow branch strategy.

    Has: main, develop, feature/xyz, release/1.0
    """
    git_dir = tmp_path / ".git"
    git_dir.mkdir()

    config_content = textwrap.dedent("""\
        [remote "origin"]
            url = git@github.com:example/gitflow-project.git
            fetch = +refs/heads/*:refs/remotes/origin/*
    """)
    (git_dir / "config").write_text(config_content)
    (git_dir / "HEAD").write_text("ref: refs/heads/develop\n")

    refs_heads = git_dir / "refs" / "heads"
    refs_heads.mkdir(parents=True)
    (refs_heads / "main").write_text("abc123\n")
    (refs_heads / "develop").write_text("def456\n")

    feature_dir = refs_heads / "feature"
    feature_dir.mkdir()
    (feature_dir / "xyz").write_text("ghi789\n")

    release_dir = refs_heads / "release"
    release_dir.mkdir()
    (release_dir / "1.0").write_text("jkl012\n")

    return tmp_path


# ---------------------------------------------------------------------------
# Infrastructure-specific fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def terraform_gcp_project(tmp_path: Path) -> Path:
    """Create a project with Terraform GCP provider."""
    (tmp_path / "main.tf").write_text(
        'provider "google" {\n  project = "my-project"\n  region  = "us-central1"\n}\n'
    )
    return tmp_path


@pytest.fixture
def terraform_aws_project(tmp_path: Path) -> Path:
    """Create a project with Terraform AWS provider."""
    (tmp_path / "main.tf").write_text(
        'provider "aws" {\n  region = "us-east-1"\n}\n'
    )
    return tmp_path


@pytest.fixture
def terraform_azure_project(tmp_path: Path) -> Path:
    """Create a project with Terraform Azure provider."""
    (tmp_path / "main.tf").write_text(
        'provider "azurerm" {\n  features {}\n}\n'
    )
    return tmp_path


@pytest.fixture
def terraform_multicloud_project(tmp_path: Path) -> Path:
    """Create a project with multiple cloud providers."""
    (tmp_path / "gcp.tf").write_text('provider "google" {\n  project = "my-project"\n}\n')
    (tmp_path / "aws.tf").write_text('provider "aws" {\n  region = "us-east-1"\n}\n')
    return tmp_path


# ---------------------------------------------------------------------------
# Orchestration-specific fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def k8s_project(tmp_path: Path) -> Path:
    """Create a project with Kubernetes manifests."""
    manifests_dir = tmp_path / "k8s"
    manifests_dir.mkdir()
    (manifests_dir / "deployment.yaml").write_text(
        textwrap.dedent("""\
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: test-app
            spec:
              replicas: 2
        """)
    )
    (manifests_dir / "service.yaml").write_text(
        textwrap.dedent("""\
            apiVersion: v1
            kind: Service
            metadata:
              name: test-app
            spec:
              type: ClusterIP
        """)
    )
    return tmp_path


@pytest.fixture
def helm_project(tmp_path: Path) -> Path:
    """Create a project with Helm chart."""
    chart_dir = tmp_path / "charts" / "myapp"
    chart_dir.mkdir(parents=True)
    (chart_dir / "Chart.yaml").write_text(
        "apiVersion: v2\nname: myapp\nversion: 1.0.0\n"
    )
    return tmp_path


@pytest.fixture
def flux_project(tmp_path: Path) -> Path:
    """Create a project with Flux GitOps configuration."""
    clusters_dir = tmp_path / "clusters" / "production"
    clusters_dir.mkdir(parents=True)
    (clusters_dir / "kustomization.yaml").write_text(
        textwrap.dedent("""\
            apiVersion: kustomize.toolkit.fluxcd.io/v1
            kind: Kustomization
            metadata:
              name: production
              namespace: flux-system
            spec:
              interval: 5m
              path: ./clusters/production
        """)
    )
    infra_dir = tmp_path / "infrastructure"
    infra_dir.mkdir()
    (infra_dir / "sources.yaml").write_text(
        textwrap.dedent("""\
            apiVersion: source.toolkit.fluxcd.io/v1
            kind: GitRepository
            metadata:
              name: flux-system
        """)
    )
    apps_dir = tmp_path / "apps"
    apps_dir.mkdir()
    return tmp_path


@pytest.fixture
def argocd_project(tmp_path: Path) -> Path:
    """Create a project with ArgoCD configuration."""
    argo_dir = tmp_path / "argocd"
    argo_dir.mkdir()
    (argo_dir / "application.yaml").write_text(
        textwrap.dedent("""\
            apiVersion: argoproj.io/v1alpha1
            kind: Application
            metadata:
              name: my-app
            spec:
              destination:
                server: https://kubernetes.default.svc
        """)
    )
    return tmp_path


@pytest.fixture
def istio_project(tmp_path: Path) -> Path:
    """Create a project with Istio service mesh annotations."""
    manifests_dir = tmp_path / "k8s"
    manifests_dir.mkdir()
    (manifests_dir / "deployment.yaml").write_text(
        textwrap.dedent("""\
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: test-app
              annotations:
                sidecar.istio.io/inject: "true"
            spec:
              replicas: 1
        """)
    )
    return tmp_path


@pytest.fixture
def linkerd_project(tmp_path: Path) -> Path:
    """Create a project with Linkerd service mesh annotations."""
    manifests_dir = tmp_path / "k8s"
    manifests_dir.mkdir()
    (manifests_dir / "deployment.yaml").write_text(
        textwrap.dedent("""\
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: test-app
              annotations:
                linkerd.io/inject: enabled
            spec:
              replicas: 1
        """)
    )
    return tmp_path


# ---------------------------------------------------------------------------
# Sample project-context.json fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def sample_project_context() -> Dict[str, Any]:
    """Return a minimal project-context.json structure (v2 format)."""
    return {
        "metadata": {
            "version": "2.0",
            "last_updated": "2026-01-01T00:00:00Z",
            "project_name": "test-project",
            "scan_config": {
                "staleness_hours": 24,
                "last_scan": "2026-01-01T00:00:00Z",
                "scanner_version": "0.1.0",
            },
        },
        "sections": {},
    }


@pytest.fixture
def sample_project_context_v1() -> Dict[str, Any]:
    """Return a v1-style project-context.json (no scan_config, old sections).

    This represents existing project-context.json files that were created
    before the gaia-scan system, with agent-enriched data.
    """
    return {
        "metadata": {
            "version": "1.0",
            "last_updated": "2025-12-01T00:00:00Z",
            "project_name": "legacy-project",
        },
        "project_details": {
            "cloud_provider": "gcp",
            "project_id": "my-gcp-project",
            "region": "us-central1",
            "project_root": "specs/",
        },
        "application_architecture": {
            "package_name": "legacy-app",
            "runtime_language": "typescript",
        },
        "development_standards": {
            "python_version": "3.11",
            "node_version": "20",
        },
        "operational_guidelines": {
            "deployment_strategy": "blue-green",
            "rollback_procedure": "manual",
        },
    }


@pytest.fixture
def sample_project_context_with_sections() -> Dict[str, Any]:
    """Return a project-context.json with scanner + agent-enriched sections."""
    return {
        "metadata": {
            "version": "2.0",
            "last_updated": "2026-01-01T00:00:00Z",
            "project_name": "test-project",
            "scan_config": {
                "staleness_hours": 24,
                "last_scan": "2026-01-01T00:00:00Z",
                "scanner_version": "0.1.0",
            },
        },
        "project_identity": {
            "_source": "scanner:stack",
            "name": "test-project",
            "type": "application",
        },
        "stack": {
            "_source": "scanner:stack",
            "languages": [{"name": "typescript", "manifest": "package.json", "primary": True}],
            "frameworks": [{"name": "express", "language": "typescript", "version": "4.18.0"}],
            "build_tools": [{"name": "npm", "detected_by": "lock_file", "lock_file": "package-lock.json"}],
        },
        "git": {
            "_source": "scanner:git",
            "platform": "github",
            "remotes": [{"name": "origin", "url": "git@github.com:example/test.git", "platform": "github"}],
            "default_branch": "main",
        },
        "environment": {
            "_source": "scanner:environment",
            "os": {"platform": "linux", "architecture": "x64", "wsl": True, "wsl_version": "2"},
            "runtimes": [{"name": "python3", "version": "3.11.5", "path": "/usr/bin/python3"}],
            "env_files": [{"name": ".env", "path": ".env"}],
            "tools": [{"name": "git", "path": "/usr/bin/git", "version": "2.40.0", "category": "git"}],
            "tool_preferences": {"file_viewer": "bat"},
        },
        "infrastructure": {
            "_source": "scanner:infrastructure",
            "cloud_providers": [{"name": "gcp", "detected_by": "terraform_provider"}],
            "iac": [{"tool": "terraform", "base_path": "terraform"}],
        },
        "operational_guidelines": {
            "deployment_strategy": "blue-green",
            "rollback_procedure": "manual",
        },
        "my_custom_notes": {
            "author": "user",
            "notes": "This is a user-custom section",
        },
    }


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def create_git_dir(
    root: Path,
    remote_url: str = "git@github.com:example/test.git",
    default_branch: str = "main",
    extra_remotes: Dict[str, str] | None = None,
    branches: list[str] | None = None,
) -> Path:
    """Helper to create a realistic .git directory structure.

    Args:
        root: Project root path.
        remote_url: URL for the origin remote.
        default_branch: Branch name for HEAD.
        extra_remotes: Additional remotes as {name: url} dict.
        branches: List of branch names to create refs for.

    Returns:
        Path to the .git directory.
    """
    git_dir = root / ".git"
    git_dir.mkdir(exist_ok=True)

    # Build config
    config_lines = ['[core]\n    repositoryformatversion = 0\n    filemode = true\n']
    config_lines.append(
        f'[remote "origin"]\n'
        f"    url = {remote_url}\n"
        f"    fetch = +refs/heads/*:refs/remotes/origin/*\n"
    )
    if extra_remotes:
        for name, url in extra_remotes.items():
            config_lines.append(
                f'[remote "{name}"]\n'
                f"    url = {url}\n"
                f"    fetch = +refs/heads/*:refs/remotes/{name}/*\n"
            )

    (git_dir / "config").write_text("".join(config_lines))
    (git_dir / "HEAD").write_text(f"ref: refs/heads/{default_branch}\n")

    # Create branch refs
    refs_heads = git_dir / "refs" / "heads"
    refs_heads.mkdir(parents=True, exist_ok=True)

    all_branches = [default_branch] + (branches or [])
    for branch in all_branches:
        branch_path = refs_heads / branch.replace("/", "/")
        branch_path.parent.mkdir(parents=True, exist_ok=True)
        branch_path.write_text("0" * 40 + "\n")

    return git_dir
