#!/usr/bin/env python3
"""
migrate_02_notes.py

Convierte los archivos .md de memoria curada -> archivo SQL con INSERT OR IGNORE.

Reglas:
  - Solo I/O sobre filesystem.
  - NO importa sqlite3.
  - Idempotente: PK = (project, name) -> INSERT OR IGNORE.
  - MEMORY.md (índice) NO se migra.
  - Frontmatter YAML mínimo: name, description, type. Opcional: originSessionId.
  - El parser de YAML es simple key:value (sin libs externas), suficiente para
    los archivos actuales que siguen ese patrón estricto.

Salida: /tmp/migrate_02_notes.sql
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

# --- Config -----------------------------------------------------------------

PROJECT = "me"
SRC_DIR = Path("/home/jorge/.claude/projects/-home-jorge-ws-me/memory")
INDEX_FILE = "MEMORY.md"  # explícitamente excluido
OUT = Path("/tmp/migrate_02_notes.sql")
VALID_TYPES = {"project", "user", "feedback"}

COLUMNS = [
    "project",
    "name",
    "type",
    "description",
    "body",
    "origin_session_id",
    "updated_at",
]


def sql_quote(value) -> str:
    if value is None:
        return "NULL"
    s = str(value)
    return "'" + s.replace("'", "''") + "'"


def parse_frontmatter(text: str):
    """
    Devuelve (front: dict, body: str).
    Si no hay frontmatter válido, front={} y body=text completo.
    """
    if not text.startswith("---"):
        return {}, text

    # Buscar el cierre.
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}, text

    end_idx = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end_idx = i
            break
    if end_idx is None:
        return {}, text

    front = {}
    for raw in lines[1:end_idx]:
        if ":" not in raw:
            continue
        key, _, val = raw.partition(":")
        key = key.strip()
        val = val.strip()
        # Quitar comillas envolventes simples o dobles si las hay.
        if len(val) >= 2 and val[0] == val[-1] and val[0] in ("'", '"'):
            val = val[1:-1]
        front[key] = val

    body = "\n".join(lines[end_idx + 1 :])
    # Quitar un único newline de cabecera dejado por la separación.
    if body.startswith("\n"):
        body = body[1:]
    return front, body


def file_iso_mtime(p: Path) -> str:
    """Timestamp ISO8601 UTC del mtime del archivo."""
    import datetime as _dt

    ts = p.stat().st_mtime
    return _dt.datetime.utcfromtimestamp(ts).strftime("%Y-%m-%dT%H:%M:%SZ")


def extract_row(md_path: Path):
    """
    Lee un .md, parsea frontmatter y devuelve la fila.
    Si el frontmatter no tiene 'type' válido, devuelve None y el caller decide.
    """
    text = md_path.read_text(encoding="utf-8")
    front, body = parse_frontmatter(text)

    note_type = (front.get("type") or "").strip().lower()
    if note_type not in VALID_TYPES:
        # Inferir por prefijo del filename como fallback.
        base = md_path.stem
        if base.startswith("project_"):
            note_type = "project"
        elif base.startswith("user_"):
            note_type = "user"
        elif base.startswith("feedback_"):
            note_type = "feedback"
        else:
            return None  # caller registra skip

    # `name` se toma del filename (estable, sin espacios) en lugar del campo
    # frontmatter que a veces es un título humano.
    name = md_path.stem

    return {
        "project": PROJECT,
        "name": name,
        "type": note_type,
        "description": front.get("description"),
        "body": body,
        "origin_session_id": front.get("originSessionId"),
        "updated_at": file_iso_mtime(md_path),
    }


def row_values_sql(row: dict) -> str:
    return "(" + ",".join(sql_quote(row.get(col)) for col in COLUMNS) + ")"


def main() -> int:
    if not SRC_DIR.exists():
        print(f"[migrate_02] ERROR: source dir not found: {SRC_DIR}", file=sys.stderr)
        return 1

    rows = []
    skipped = []
    files = sorted(p for p in SRC_DIR.iterdir() if p.is_file() and p.suffix == ".md")

    for p in files:
        if p.name == INDEX_FILE:
            continue  # MEMORY.md es el índice, no se migra.
        row = extract_row(p)
        if row is None:
            skipped.append(p.name)
            continue
        rows.append(row)

    cols_csv = ",".join(COLUMNS)
    insert_prefix = f"INSERT OR IGNORE INTO notes ({cols_csv}) VALUES\n"

    with OUT.open("w", encoding="utf-8") as out:
        out.write("-- Generated by migrate_02_notes.py (idempotent)\n")
        out.write(f"-- Source dir: {SRC_DIR}\n")
        out.write(f"-- Files considered: {len(files)} (excluyendo {INDEX_FILE})\n")
        out.write(f"-- Records to insert: {len(rows)}\n")
        out.write(f"-- Skipped: {len(skipped)} -> {skipped}\n")
        out.write("BEGIN TRANSACTION;\n")
        if rows:
            out.write(insert_prefix)
            out.write(",\n".join(row_values_sql(r) for r in rows))
            out.write(";\n")
        out.write("COMMIT;\n")

    print(f"[migrate_02] wrote {OUT} ({len(rows)} rows, {len(skipped)} skipped)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
