#!/usr/bin/env python3
"""
migrate_02_memory.py

Convierte los archivos .md de memoria curada -> archivo SQL con INSERT OR IGNORE.

Reglas:
  - Solo I/O sobre filesystem.
  - NO importa sqlite3.
  - Idempotente: PK = (project, name) -> INSERT OR IGNORE.
  - MEMORY.md (índice) NO se migra.
  - Frontmatter YAML mínimo: name, description, type. Opcional: originSessionId.

CLI args (parametrización cross-workspace):
  --project   workspace name (default: 'me')
  --src       directorio con .md files (default: ws/me memory)
  --out       path al SQL de salida (default: /tmp/migrate_02_memory.sql)
  --fragment  emite solo INSERTs (sin BEGIN/COMMIT)
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

DEFAULT_PROJECT = "me"
DEFAULT_SRC_DIR = Path("/home/jorge/.claude/projects/-home-jorge-ws-me/memory")
DEFAULT_OUT = Path("/tmp/migrate_02_memory.sql")
INDEX_FILE = "MEMORY.md"
VALID_TYPES = {"project", "user", "feedback"}

COLUMNS = [
    "project",
    "name",
    "type",
    "description",
    "body",
    "origin_session_id",
    "updated_at",
]


def sql_quote(value) -> str:
    if value is None:
        return "NULL"
    s = str(value)
    return "'" + s.replace("'", "''") + "'"


def parse_frontmatter(text: str):
    if not text.startswith("---"):
        return {}, text

    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}, text

    end_idx = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end_idx = i
            break
    if end_idx is None:
        return {}, text

    front = {}
    for raw in lines[1:end_idx]:
        if ":" not in raw:
            continue
        key, _, val = raw.partition(":")
        key = key.strip()
        val = val.strip()
        if len(val) >= 2 and val[0] == val[-1] and val[0] in ("'", '"'):
            val = val[1:-1]
        front[key] = val

    body = "\n".join(lines[end_idx + 1 :])
    if body.startswith("\n"):
        body = body[1:]
    return front, body


def file_iso_mtime(p: Path) -> str:
    import datetime as _dt

    ts = p.stat().st_mtime
    return _dt.datetime.utcfromtimestamp(ts).strftime("%Y-%m-%dT%H:%M:%SZ")


def extract_row(md_path: Path, project: str):
    text = md_path.read_text(encoding="utf-8")
    front, body = parse_frontmatter(text)

    note_type = (front.get("type") or "").strip().lower()
    if note_type not in VALID_TYPES:
        base = md_path.stem
        if base.startswith("project_"):
            note_type = "project"
        elif base.startswith("user_"):
            note_type = "user"
        elif base.startswith("feedback_"):
            note_type = "feedback"
        else:
            # Fallback final: tratar cualquier .md sin prefijo como 'project' note.
            # Necesario para workspaces aaxis donde los nombres no siguen prefijo (ej. wsl_mirrored_docker_setup).
            note_type = "project"

    name = md_path.stem

    return {
        "project": project,
        "name": name,
        "type": note_type,
        "description": front.get("description"),
        "body": body,
        "origin_session_id": front.get("originSessionId"),
        "updated_at": file_iso_mtime(md_path),
    }


def row_values_sql(row: dict) -> str:
    return "(" + ",".join(sql_quote(row.get(col)) for col in COLUMNS) + ")"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate INSERT SQL for memory table.")
    parser.add_argument("--project", default=DEFAULT_PROJECT)
    parser.add_argument("--src", default=str(DEFAULT_SRC_DIR), help="memory dir with .md files")
    parser.add_argument("--out", default=str(DEFAULT_OUT))
    parser.add_argument("--fragment", action="store_true")
    args = parser.parse_args()

    project = args.project
    src_dir = Path(args.src)
    out = Path(args.out)
    fragment = args.fragment

    if not src_dir.exists():
        print(f"[migrate_02:{project}] ERROR: source dir not found: {src_dir}", file=sys.stderr)
        return 1

    rows = []
    skipped = []
    files = sorted(p for p in src_dir.iterdir() if p.is_file() and p.suffix == ".md")

    for p in files:
        if p.name == INDEX_FILE:
            continue
        row = extract_row(p, project)
        if row is None:
            skipped.append(p.name)
            continue
        rows.append(row)

    cols_csv = ",".join(COLUMNS)
    insert_prefix = f"INSERT OR IGNORE INTO memory ({cols_csv}) VALUES\n"

    with out.open("w", encoding="utf-8") as fh:
        fh.write(f"-- Generated by migrate_02_memory.py (idempotent)\n")
        fh.write(f"-- Project: {project}\n")
        fh.write(f"-- Source dir: {src_dir}\n")
        fh.write(f"-- Files considered: {len(files)} (excluyendo {INDEX_FILE})\n")
        fh.write(f"-- Records to insert: {len(rows)}\n")
        fh.write(f"-- Skipped: {len(skipped)} -> {skipped}\n")
        if not fragment:
            fh.write("BEGIN TRANSACTION;\n")
        if rows:
            fh.write(insert_prefix)
            fh.write(",\n".join(row_values_sql(r) for r in rows))
            fh.write(";\n")
        if not fragment:
            fh.write("COMMIT;\n")

    print(f"[migrate_02:{project}] wrote {out} ({len(rows)} rows, {len(skipped)} skipped)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
