#!/usr/bin/env python3
"""
migrate_04_harness_events.py

Convierte events.jsonl -> archivo SQL con INSERT batched.

Reglas:
  - Solo I/O sobre filesystem.
  - NO importa sqlite3.
  - `id` es AUTOINCREMENT en la tabla; NO lo insertamos.
  - `payload` = json.dumps(record) entero -- preserva todos los campos.
  - Idempotencia: harness_events NO tiene UNIQUE constraint útil.
    Aplicar una sola vez. Re-ejecuciones requieren DELETE WHERE project=...

CLI args (parametrización cross-workspace):
  --project   workspace name (default: 'me')
  --src       path al events.jsonl (default: ws/me)
  --out       path al SQL de salida (default: /tmp/migrate_04_harness_events.sql)
  --fragment  emite solo INSERTs (sin BEGIN/COMMIT)
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

DEFAULT_PROJECT = "me"
DEFAULT_SRC = Path("/home/jorge/ws/me/.claude/events/events.jsonl")
DEFAULT_OUT = Path("/tmp/migrate_04_harness_events.sql")
BATCH_SIZE = 200

COLUMNS = ["project", "ts", "type", "source", "agent", "result", "severity", "payload"]


def sql_quote(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        if isinstance(value, float) and (value != value or value in (float("inf"), float("-inf"))):
            return "NULL"
        return str(value)
    s = str(value)
    return "'" + s.replace("'", "''") + "'"


def extract_row(record: dict, project: str) -> dict:
    return {
        "project": project,
        "ts": record.get("ts"),
        "type": record.get("type"),
        "source": record.get("source"),
        "agent": record.get("agent"),
        "result": record.get("result"),
        "severity": record.get("severity"),
        "payload": json.dumps(record, ensure_ascii=False, separators=(",", ":")),
    }


def row_values_sql(row: dict) -> str:
    return "(" + ",".join(sql_quote(row.get(col)) for col in COLUMNS) + ")"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate INSERT SQL for harness_events table.")
    parser.add_argument("--project", default=DEFAULT_PROJECT)
    parser.add_argument("--src", default=str(DEFAULT_SRC), help="path to events.jsonl")
    parser.add_argument("--out", default=str(DEFAULT_OUT))
    parser.add_argument("--fragment", action="store_true")
    args = parser.parse_args()

    project = args.project
    src = Path(args.src)
    out = Path(args.out)
    fragment = args.fragment

    if not src.exists():
        print(f"[migrate_04:{project}] ERROR: source not found: {src}", file=sys.stderr)
        return 1

    rows = []
    skipped = 0
    total_lines = 0

    with src.open("r", encoding="utf-8") as f:
        for line in f:
            total_lines += 1
            s = line.strip()
            if not s:
                continue
            try:
                rec = json.loads(s)
            except json.JSONDecodeError:
                skipped += 1
                continue
            if not rec.get("ts") or not rec.get("type"):
                skipped += 1
                continue
            rows.append(extract_row(rec, project))

    cols_csv = ",".join(COLUMNS)
    insert_prefix = f"INSERT INTO harness_events ({cols_csv}) VALUES\n"

    with out.open("w", encoding="utf-8") as fh:
        fh.write(f"-- Generated by migrate_04_harness_events.py\n")
        fh.write(f"-- Project: {project}\n")
        fh.write(f"-- Source: {src}\n")
        fh.write(f"-- Total source lines: {total_lines}\n")
        fh.write(f"-- Records to insert:  {len(rows)}\n")
        fh.write(f"-- Skipped:            {skipped}\n")
        fh.write("--\n")
        fh.write("-- WARNING: harness_events sin PK natural; aplicar 2 veces duplica filas.\n")
        if not fragment:
            fh.write("BEGIN TRANSACTION;\n")

        for i in range(0, len(rows), BATCH_SIZE):
            batch = rows[i : i + BATCH_SIZE]
            fh.write(insert_prefix)
            fh.write(",\n".join(row_values_sql(r) for r in batch))
            fh.write(";\n")

        if not fragment:
            fh.write("COMMIT;\n")

    print(f"[migrate_04:{project}] wrote {out} ({len(rows)} rows, {skipped} skipped)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
