#!/usr/bin/env python3
"""
migrate_03_context_sections.py

Convierte project-context.json -> archivo SQL con INSERT OR IGNORE.

Reglas:
  - Solo I/O sobre filesystem.
  - NO importa sqlite3.
  - Idempotente: PK = (project, section_name).
  - Cada sección de top-level "sections" es una fila; payload = json.dumps(value).
  - metadata = json.dumps(top-level metadata) -- replicado en cada fila para que
    una sola sección lleve consigo el contexto de versionado/scan.

Salida: /tmp/migrate_03_context_sections.sql
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

# --- Config -----------------------------------------------------------------

PROJECT = "me"
SRC = Path("/home/jorge/ws/me/.claude/project-context/project-context.json")
OUT = Path("/tmp/migrate_03_context_sections.sql")

COLUMNS = ["project", "section_name", "payload", "metadata", "updated_at"]


def sql_quote(value) -> str:
    if value is None:
        return "NULL"
    s = str(value)
    return "'" + s.replace("'", "''") + "'"


def row_values_sql(row: dict) -> str:
    return "(" + ",".join(sql_quote(row.get(col)) for col in COLUMNS) + ")"


def main() -> int:
    if not SRC.exists():
        print(f"[migrate_03] ERROR: source not found: {SRC}", file=sys.stderr)
        return 1

    data = json.loads(SRC.read_text(encoding="utf-8"))
    metadata = data.get("metadata") or {}
    sections = data.get("sections") or {}

    metadata_text = json.dumps(metadata, ensure_ascii=False, separators=(",", ":"))
    updated_at = metadata.get("last_updated")

    rows = []
    for section_name, payload in sections.items():
        rows.append(
            {
                "project": PROJECT,
                "section_name": section_name,
                "payload": json.dumps(payload, ensure_ascii=False, separators=(",", ":")),
                "metadata": metadata_text,
                "updated_at": updated_at,
            }
        )

    cols_csv = ",".join(COLUMNS)
    insert_prefix = f"INSERT OR IGNORE INTO context_sections ({cols_csv}) VALUES\n"

    with OUT.open("w", encoding="utf-8") as out:
        out.write("-- Generated by migrate_03_context_sections.py (idempotent)\n")
        out.write(f"-- Source: {SRC}\n")
        out.write(f"-- Sections to insert: {len(rows)}\n")
        out.write("BEGIN TRANSACTION;\n")
        if rows:
            out.write(insert_prefix)
            out.write(",\n".join(row_values_sql(r) for r in rows))
            out.write(";\n")
        out.write("COMMIT;\n")

    print(f"[migrate_03] wrote {OUT} ({len(rows)} rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
