#!/usr/bin/env python3
"""
migrate_04_harness_events.py

Convierte events.jsonl -> archivo SQL con INSERT batched.

Reglas:
  - Solo I/O sobre filesystem.
  - NO importa sqlite3.
  - `id` es AUTOINCREMENT en la tabla; NO lo insertamos.
  - `payload` = json.dumps(record) entero -- preserva todos los campos.
  - Idempotencia: la tabla harness_events NO tiene UNIQUE constraint útil
    (no hay PK natural), así que aquí confiamos en que el wrapper aplique el
    SQL una sola vez. Para re-ejecuciones idempotentes, el hash (ts,type,source,
    agent,result,severity) podría usarse, pero el schema actual no lo expone.
    Estrategia: regenerar el .sql siempre desde la fuente; si se aplica dos
    veces, habrá duplicados. Mitigación recomendada: validar V4 antes y abortar.

Salida: /tmp/migrate_04_harness_events.sql
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

# --- Config -----------------------------------------------------------------

PROJECT = "me"
SRC = Path("/home/jorge/ws/me/.claude/events/events.jsonl")
OUT = Path("/tmp/migrate_04_harness_events.sql")
BATCH_SIZE = 200  # eventos cortos -> batch grande

# Excluimos `id` -- AUTOINCREMENT.
COLUMNS = ["project", "ts", "type", "source", "agent", "result", "severity", "payload"]


def sql_quote(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        if isinstance(value, float) and (value != value or value in (float("inf"), float("-inf"))):
            return "NULL"
        return str(value)
    s = str(value)
    return "'" + s.replace("'", "''") + "'"


def extract_row(record: dict) -> dict:
    return {
        "project": PROJECT,
        "ts": record.get("ts"),
        "type": record.get("type"),
        "source": record.get("source"),
        "agent": record.get("agent"),
        "result": record.get("result"),
        "severity": record.get("severity"),
        # payload completo preserva campos extra (`meta`, etc.)
        "payload": json.dumps(record, ensure_ascii=False, separators=(",", ":")),
    }


def row_values_sql(row: dict) -> str:
    return "(" + ",".join(sql_quote(row.get(col)) for col in COLUMNS) + ")"


def main() -> int:
    if not SRC.exists():
        print(f"[migrate_04] ERROR: source not found: {SRC}", file=sys.stderr)
        return 1

    rows = []
    skipped = 0
    total_lines = 0

    with SRC.open("r", encoding="utf-8") as f:
        for line in f:
            total_lines += 1
            s = line.strip()
            if not s:
                continue
            try:
                rec = json.loads(s)
            except json.JSONDecodeError:
                skipped += 1
                continue
            # ts y type son NOT NULL en el schema; descartar registros que no
            # los traen para no romper el INSERT.
            if not rec.get("ts") or not rec.get("type"):
                skipped += 1
                continue
            rows.append(extract_row(rec))

    cols_csv = ",".join(COLUMNS)
    # NOTA: harness_events no tiene unique constraint -> usamos INSERT (no IGNORE).
    # La idempotencia para este dominio se logra por flujo: aplicar el .sql una
    # sola vez. Si se necesita re-aplicar, antes hacer DELETE WHERE project='me'.
    insert_prefix = f"INSERT INTO harness_events ({cols_csv}) VALUES\n"

    with OUT.open("w", encoding="utf-8") as out:
        out.write("-- Generated by migrate_04_harness_events.py\n")
        out.write(f"-- Source: {SRC}\n")
        out.write(f"-- Total source lines: {total_lines}\n")
        out.write(f"-- Records to insert:  {len(rows)}\n")
        out.write(f"-- Skipped:            {skipped}\n")
        out.write("--\n")
        out.write("-- WARNING: harness_events no tiene PK natural; aplicar 2 veces duplica filas.\n")
        out.write("-- Para re-ejecutar limpiamente: DELETE FROM harness_events WHERE project='me'; antes.\n")
        out.write("BEGIN TRANSACTION;\n")

        for i in range(0, len(rows), BATCH_SIZE):
            batch = rows[i : i + BATCH_SIZE]
            out.write(insert_prefix)
            out.write(",\n".join(row_values_sql(r) for r in batch))
            out.write(";\n")

        out.write("COMMIT;\n")

    print(f"[migrate_04] wrote {OUT} ({len(rows)} rows, {skipped} skipped)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
