"""
Test schema compatibility between CLAUDE.template.md jq query and gaia-init.js output.

Ensures the orchestrator's bootstrap jq command references fields that
actually exist in the project-context.json schema generated by gaia-init.
"""

import json
import re
import pytest
from pathlib import Path


class TestSchemaCompatibility:
    """Verify CLAUDE.template.md jq paths match gaia-init.js schema."""

    @pytest.fixture
    def package_root(self):
        return Path(__file__).resolve().parents[2]

    @pytest.fixture
    def template_content(self, package_root):
        template_path = package_root / "templates" / "CLAUDE.template.md"
        assert template_path.exists(), "CLAUDE.template.md not found"
        return template_path.read_text()

    @pytest.fixture
    def gaia_init_content(self, package_root):
        init_path = package_root / "bin" / "gaia-init.js"
        assert init_path.exists(), "gaia-init.js not found"
        return init_path.read_text()

    @pytest.fixture
    def fixture_contexts(self, package_root):
        """Load all test fixture project-context files."""
        fixtures_dir = package_root / "tests" / "fixtures"
        contexts = {}
        for f in fixtures_dir.glob("project-context.*.json"):
            contexts[f.stem] = json.loads(f.read_text())
        return contexts

    def _extract_jq_paths(self, template_content):
        """Extract dotted paths from the jq command in the template."""
        jq_block = re.search(r"```bash\njq '\{(.*?)\}'", template_content, re.DOTALL)
        assert jq_block, "Could not find jq block in template"

        jq_body = jq_block.group(1)
        # Match full dotted paths like .metadata.project_name or .sections.project_details.cluster_name
        paths = re.findall(r'\.((?:metadata|sections|paths)(?:\.\w+)+)', jq_body)
        return paths

    def test_template_has_jq_command(self, template_content):
        """Template must contain a jq command for Quick Context."""
        assert "jq '{" in template_content, "Template missing jq Quick Context command"

    def test_jq_references_valid_top_level_sections(self, template_content):
        """All jq dotted paths must reference sections that gaia-init generates."""
        valid_sections = {
            "metadata",
            "sections.project_details",
            "sections.terraform_infrastructure",
            "sections.gitops_configuration",
            "sections.application_services",
            "sections.operational_guidelines",
        }

        paths = self._extract_jq_paths(template_content)
        for path in paths:
            parts = path.split(".")
            # metadata.X → check "metadata"; sections.Y.Z → check "sections.Y"
            if parts[0] == "sections" and len(parts) >= 2:
                top_section = f"{parts[0]}.{parts[1]}"
            else:
                top_section = parts[0]
            assert top_section in valid_sections, (
                f"jq references '{path}' but top-level section '{top_section}' "
                f"is not generated by gaia-init. Valid sections: {valid_sections}"
            )

    def test_fixture_contexts_have_expected_structure(self, fixture_contexts):
        """Test fixture project-context files must have the sections gaia-init generates."""
        if not fixture_contexts:
            pytest.skip("No fixture project-context files found")

        for name, ctx in fixture_contexts.items():
            assert "metadata" in ctx, f"{name}: missing metadata"
            assert "sections" in ctx, f"{name}: missing sections"

    def test_template_path_matches_gaia_init_output(self, template_content, gaia_init_content):
        """Template must reference the same file path that gaia-init writes to."""
        assert ".claude/project-context/project-context.json" in template_content, (
            "Template jq must reference .claude/project-context/project-context.json"
        )
        assert "'.claude', 'project-context', 'project-context.json'" in gaia_init_content or \
               "'project-context', 'project-context.json'" in gaia_init_content, (
            "gaia-init must write to .claude/project-context/project-context.json"
        )
